In [7]:
import os
import pandas as pd

In [8]:
runs = os.listdir('../runs/')

results = []

for i, run in enumerate(runs):
    result_json = os.path.join('../runs', run, 'results.json')
    try:
        results.append(pd.read_json(result_json, orient='records'))
    except:
        pass

results_df = pd.concat(results).sort_values(by=['ds_name', 'model']).reset_index(drop=True)

In [9]:
results_df.loc[:, 'train_mse_mean']= results_df.loc[:, 'train_mse'].apply(lambda x: x['mean'])
results_df.loc[:, 'train_mse_std']= results_df.loc[:, 'train_mse'].apply(lambda x: x['std'])

results_df.loc[:, 'test_mse_mean']= results_df.loc[:, 'test_mse'].apply(lambda x: x['mean'])
results_df.loc[:, 'test_mse_std']= results_df.loc[:, 'test_mse'].apply(lambda x: x['std'])

In [12]:
results_summary = results_df.loc[:, ['run_name', 'ds_name', 'model', 'train_mse_mean', 'train_mse_std', 'test_mse_mean', 'test_mse_std', 'energy_score']]

results_summary_intensity = results_summary.loc[results_summary.run_name.str.contains('intensity')].drop(columns=['run_name'])

results_summary_intensity

,ds_name,model,train_mse_mean,train_mse_std,test_mse_mean,test_mse_std,energy_score
0,north_indian_ocean,BayesLSTM,0.000547,0.000004,0.000304,0.000004,0.004906
2,north_indian_ocean,BayesRNN,0.000780,0.000022,0.000556,0.000047,0.019647
4,north_west_pacific_ocean,BayesLSTM,0.002030,0.000006,0.001157,0.000008,0.004620
6,north_west_pacific_ocean,BayesRNN,0.003149,0.000461,0.002229,0.000790,0.012534
8,south_indian_ocean,BayesLSTM,0.001298,0.000009,0.001304,0.000014,0.014150
10,south_indian_ocean,BayesRNN,0.002032,0.000251,0.002139,0.000469,0.030133
12,south_pacific_ocean,BayesLSTM,0.001755,0.000022,0.001890,0.000037,0.017635
14,south_pacific_ocean,BayesRNN,0.001711,0.000169,0.001925,0.000308,0.023566

In [13]:
results_summary_location = results_summary.loc[results_summary.run_name.str.contains('location')].drop(columns=['run_name'])

results_summary_location

,ds_name,model,train_mse_mean,train_mse_std,test_mse_mean,test_mse_std,energy_score
1,north_indian_ocean,BayesLSTM,0.000492,0.000004,0.000492,0.000007,0.007405
3,north_indian_ocean,BayesRNN,0.000879,0.000176,0.000884,0.000281,0.016733
5,north_west_pacific_ocean,BayesLSTM,0.000348,0.000003,0.000354,0.000005,0.010932
7,north_west_pacific_ocean,BayesRNN,0.000746,0.000216,0.000822,0.000281,0.013558
9,south_indian_ocean,BayesLSTM,0.000210,0.000002,0.000206,0.000002,0.007092
11,south_indian_ocean,BayesRNN,0.000876,0.000203,0.000845,0.000248,0.009819
13,south_pacific_ocean,BayesLSTM,0.000422,0.000004,0.000400,0.000007,0.012847
15,south_pacific_ocean,BayesRNN,0.000792,0.000173,0.000784,0.000355,0.014445