In [7]:
import os
import pandas as pd

In [8]:
runs = os.listdir('../runs/')

results = []

for i, run in enumerate(runs):
    result_json = os.path.join('../runs', run, 'results.json')
    try:
        results.append(pd.read_json(result_json, orient='records'))
    except:
        pass

results_df = pd.concat(results).sort_values(by=['ds_name', 'model']).reset_index(drop=True)

In [9]:
results_df.loc[:, 'train_rmse_mean']= results_df.loc[:, 'train_rmse'].apply(lambda x: x['mean'])
results_df.loc[:, 'train_rmse_std']= results_df.loc[:, 'train_rmse'].apply(lambda x: x['std'])

results_df.loc[:, 'test_rmse_mean']= results_df.loc[:, 'test_rmse'].apply(lambda x: x['mean'])
results_df.loc[:, 'test_rmse_std']= results_df.loc[:, 'test_rmse'].apply(lambda x: x['std'])

In [10]:
# pd.set_option('display.float_format', lambda x: '%.2e' % x)

In [11]:
results_summary = results_df.loc[:, ['run_name', 'ds_name', 'model', 'train_rmse_mean', 'train_rmse_std', 'test_rmse_mean', 'test_rmse_std', 'train_es', 'test_es']]

results_summary_intensity = results_summary.loc[results_summary.run_name.str.contains('intensity')].drop(columns=['run_name'])

results_summary_intensity

,ds_name,model,train_rmse_mean,train_rmse_std,test_rmse_mean,test_rmse_std,train_es,test_es
0,north_indian_ocean,BayesLSTM,0.046817,0.000097,0.073270,0.000174,0.057043,0.049032
2,north_indian_ocean,BayesRNN,0.069009,0.000368,0.119762,0.000886,0.047275,0.027772
4,north_west_pacific_ocean,BayesLSTM,0.045124,0.000069,0.034177,0.000111,0.014074,0.004414
6,north_west_pacific_ocean,BayesRNN,0.059464,0.002612,0.052226,0.004585,0.041321,0.022475
8,south_indian_ocean,BayesLSTM,0.036819,0.000132,0.036987,0.000198,0.032626,0.012918
10,south_indian_ocean,BayesRNN,0.041776,0.002575,0.042105,0.003652,0.019396,0.028229
12,south_pacific_ocean,BayesLSTM,0.037928,0.000180,0.039627,0.000286,0.011200,0.018960
14,south_pacific_ocean,BayesRNN,0.041532,0.002143,0.044315,0.003502,0.025249,0.020752

In [12]:
results_summary_location = results_summary.loc[results_summary.run_name.str.contains('location')].drop(columns=['run_name'])

results_summary_location

,ds_name,model,train_rmse_mean,train_rmse_std,test_rmse_mean,test_rmse_std,train_es,test_es
1,north_indian_ocean,BayesLSTM,0.016786,0.000072,0.016818,0.000116,0.003351,0.005597
3,north_indian_ocean,BayesRNN,0.030170,0.002581,0.030836,0.003727,0.002749,0.010284
5,north_west_pacific_ocean,BayesLSTM,0.019868,0.000087,0.020140,0.000130,0.005895,0.010603
7,north_west_pacific_ocean,BayesRNN,0.036032,0.003727,0.035435,0.006033,0.010682,0.016920
9,south_indian_ocean,BayesLSTM,0.020013,0.000080,0.019883,0.000118,0.002695,0.006548
11,south_indian_ocean,BayesRNN,0.033852,0.002907,0.033743,0.004011,0.001667,0.016212
13,south_pacific_ocean,BayesLSTM,0.022631,0.000111,0.022422,0.000178,0.006599,0.014262
15,south_pacific_ocean,BayesRNN,0.036242,0.003053,0.036448,0.004998,0.007348,0.022082